package eu.chorevolution.cd.utility.sia.endpoints.manager.baseservice;

import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.1.6
 * 2017-03-21T11:24:49.605+01:00
 * Generated source version: 3.1.6
 * 
 */
@WebServiceClient(name = "cdSEADA-SEARPBaseService", 
                  wsdlLocation = "classpath:BaseService.wsdl",
                  targetNamespace = "http://services.chorevolution.eu/") 
public class CdSEADASEARPBaseService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://services.chorevolution.eu/", "cdSEADA-SEARPBaseService");
    public final static QName ConfigurableServicePort = new QName("http://services.chorevolution.eu/", "ConfigurableServicePort");
    static {
        URL url = CdSEADASEARPBaseService.class.getClassLoader().getResource("BaseService.wsdl");
        if (url == null) {
            java.util.logging.Logger.getLogger(CdSEADASEARPBaseService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "classpath:BaseService.wsdl");
        }       
        WSDL_LOCATION = url;   
    }

    public CdSEADASEARPBaseService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public CdSEADASEARPBaseService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public CdSEADASEARPBaseService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    public CdSEADASEARPBaseService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public CdSEADASEARPBaseService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public CdSEADASEARPBaseService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }    




    /**
     *
     * @return
     *     returns ConfigurableService
     */
    @WebEndpoint(name = "ConfigurableServicePort")
    public ConfigurableService getConfigurableServicePort() {
        return super.getPort(ConfigurableServicePort, ConfigurableService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ConfigurableService
     */
    @WebEndpoint(name = "ConfigurableServicePort")
    public ConfigurableService getConfigurableServicePort(WebServiceFeature... features) {
        return super.getPort(ConfigurableServicePort, ConfigurableService.class, features);
    }

}
