package eu.chorevolution.cd.utility.sia.endpoints.manager.baseservice;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.1.6
 * 2017-03-21T11:24:49.550+01:00
 * Generated source version: 3.1.6
 * 
 */
@WebService(targetNamespace = "http://services.chorevolution.eu/", name = "ConfigurableService")
@XmlSeeAlso({ObjectFactory.class})
public interface ConfigurableService {

    @WebMethod
    @Action(input = "http://services.chorevolution.eu/ConfigurableService/setInvocationAddressRequest", output = "http://services.chorevolution.eu/ConfigurableService/setInvocationAddressResponse")
    @RequestWrapper(localName = "setInvocationAddress", targetNamespace = "http://services.chorevolution.eu/", className = "eu.chorevolution.cd.utility.sia.endpoints.manager.baseservice.SetInvocationAddress")
    @ResponseWrapper(localName = "setInvocationAddressResponse", targetNamespace = "http://services.chorevolution.eu/", className = "eu.chorevolution.cd.utility.sia.endpoints.manager.baseservice.SetInvocationAddressResponse")
    public void setInvocationAddress(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        java.lang.String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        java.util.List<java.lang.String> arg2
    );
}
